### ISSUE TITLE
final max-age calculated by max-age + stale-while-revalidate 

### ISSUE THREAD

**Issue by Christian-Krupa** [DracoBlue/lua-native-ssi-nginx#14]
our website use the stale-while-revalidate attribute. this is an performance improvement and we know that the content may be cached longer than it is defined in the "max-age" attribute. it would be great to get an option (configuration, request header or parameter) to use max-age + stale-while-revalidate for the final cache time calculation.

eg:
ssi-response-header: 
max-age=20, stale-while-revalidate=40
age=25

i would expect the following lua-native-ssi-nginx response:
max-age: 35

we need this because atm stale content results in an "no-cache" response wich effectively turn our caching cdn into an none caching cdn.

**Comment by DracoBlue** [comment]
#16

**Comment by DracoBlue** [comment]
Added https://github.com/DracoBlue/lua-native-ssi-nginx/blob/use-swr-to-min-max-cache/tests/use_minimized_max_age_and_swr.sh to test this case.
