### ISSUE TITLE
debug http-parameter

### ISSUE THREAD

**Issue by Christian-Krupa** [DracoBlue/lua-native-ssi-nginx#17]
currently it is hard to identify why an url got an low max-age cache header. i need to enable nginx debug log. restart nginx and do a lot of grep magic.

it would be nice to append an http request parameter which tells me the ssi url with the lowest cache time within the request. an response header seems to be an nice option without changing the nginx config.

**Comment by Christian-Krupa** [comment]
Request: 
`domain.com/ssiurl?lua-native-ssi-nginx-debug=true`
Response:
`Cache-Control: "max-age=0 ...."`
`X-Lua-SSI-Min-Cache-Url: "domain.com/some-url"`
`X-Lua-SSI-Min-Cache-Control: "max-age=0"`

**Comment by DracoBlue** [comment]
With lua-ntive-ssi-nginx 1.6.0 you can use it like this:

```console
$ curl -v -sS -H 'X-Ssi-Debug: true' "http://localhost:4778/max-age/include-stale-expires-in-120.json" 2>&1
< X-Ssi-Minimize-MaxAge-Url: /max-age/35-seconds/30-age/40-swr
< X-Ssi-Minimize-MaxAge-Age: 45
< X-Ssi-Minimize-MaxAge-Cache-Control: max-age=35, stale-while-revalidate=40
```

**Comment by DracoBlue** [comment]
ps: I hope a request header is enough for your use case!
